POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name":"Vegeta",
    "email":"vegeta@gmail.com",
    "password":"kakarotoinseto"
    
}

###
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email":"vegeta@gmail.com",
    "password":"kakarotoinseto"
    
}

###
POST http://localhost:3003/post/create
Authorization:{{login.response.body.token}}
Content-Type: application/json

{
    "content":"Pincipe dos sayajins"
}

###
GET http://localhost:3003/post/
Authorization:{{login.response.body.token}}

###
DELETE http://localhost:3003/post/90f995ca-047a-47fb-8c6a-7d816b3f739c
Authorization:{{login.response.body.token}}
